### ISSUE TITLE
wordpress cookies needed in routes.yaml?

### ISSUE THREAD

**Issue by gilzow** [platformsh/template-wordpress#21]
Using this repo as a starting point for a wordpress site on platform.sh.  Got everything up and running up until the point at which I needed to log in.  WordPress indicated cookies were being blocked. Checked WPCLI against the cookies that were being set to ensure domains & path were correct.  Was unable to get it to work until I added `'/^wordpress_/'` for cookies in the routes.yaml file, similar to how it is in the D8 template for Drupal cookies.  After that I was WordPress was able to "see" the cookies it had set. 

Our Enterprise Architect Royall Spence suggested I post my issue here. Happy to provide more information.

**Comment by gormus** [comment]
@gilzow Here are the complete list of cookies you should whitelist in `routes.yaml`: https://github.com/platformsh/template-wordpress/pull/22/commits/fdfe0da70cdcdfd4b9ada5da8a3d5de08bd8d79d

**Comment by gilzow** [comment]
AH, I did forget about the `wp-settings` cookie.  
Will that commit be merged in the near future?
