### ISSUE TITLE
Wrong declaration of custom install paths

### ISSUE THREAD

**Issue by markushausammann** [platformsh/template-wordpress#9]
Currently, you're passing strings to the custom installer paths, but `array()` is expected. The correct configuration is this:

```
"extra": {
    "wordpress-install-dir": "web/wp",
    "installer-paths": {
      "web/wp-content/plugins/{$name}": ["type:wordpress-plugin"],
      "web/wp-content/themes/{$name}": ["type:wordpress-theme"],
      "web/wp-content/mu-plugins/{$name}": ["type:wordpress-muplugin"]
    }
  }
```

**Comment by Crell** [comment]
That looks like an issue with the build script that produces this repository.  I've updated the build script and filed a PR to fix it here.  Thanks!
